### ISSUE TITLE
reCaptcha why not have it monocrome?

### ISSUE THREAD

**Issue by RaitaroH** [tkosamja/css-themes#1]
![image](https://user-images.githubusercontent.com/19552720/34637835-31f2a218-f2c7-11e7-9fec-33c99a606eb7.png)
I think it looks much better and it fits more with any page.
 
EDIT: Sorry for the little white icon over there. I had to disable the jumping cursor in KDE because it is messing with my screenshots.

**Comment by tkosamja** [comment]
Fixed in cecaab43616001545b90ae51bd66c0449fb9b48f
